Repository wrappid/wrappid-service, pull requests merged in 2024-01, with the labels that each got.

#16 feat: Enhancement wrappid config file
  wrappid.conf.json
Labels: enhancement

#22 feat: setup swagger called with wrappidApp, swaggerJsonFile
  src/swagger-output.json
  src/wrappidApp.js
Labels: documentation

#21 feat: Add basic eslint rules
  .eslintrc.js
  package.json
  src/modules/_system/controllers.registry.js
  src/modules/_system/controllers/_system.controller.js
  src/modules/_system/controllers/test.controller.js
  src/modules/_system/functions.registry.js
  src/modules/_system/functions/test.functions.js
  src/modules/_system/middlewares.registry.js
  src/modules/_system/middlewares/test.middleware.js
  src/modules/_system/models.registry.js
  src/modules/_system/models/TestDatas.model.js
  src/modules/_system/tasks.registry.js
  src/modules/_system/tasks/TestTask.js
  src/registry/ControllersRegistry.js
  src/registry/FunctionsRegistry.js
  src/registry/MiddlewaresRegistry.js
  src/registry/ModelsRegistry.js
  src/registry/TasksRegistry.js
  src/registry/ValidationsRegistry.js
  src/registry/index.js
  src/server.js
  src/wrappidApp.js
Labels: enhancement

#26 docs: 🔒 license added
  LICENSE
Labels: documentation

#29 fix: :bug: add missing dependency
  package.json
Labels: bug

#30 ci(config): :wrench: add branch rules and code format rules
  .github/pull_request_template.md
  .github/workflows/pr-guardrails.yml
  .husky/pre-commit
  lint-staged.config.js
  package-lock.json
  package.json
  src/wrappidApp.js
Labels: enhancement

#34 ci(config): :wrench: modify husky script
  .husky/pre-commit
  .vscode/settings.json
  package-lock.json
  package.json
Labels: enhancement

#35 Merge development into main
  .github/pull_request_template.md
  .github/workflows/pr-guardrails.yml
  .husky/pre-commit
  .vscode/settings.json
  lint-staged.config.js
  package-lock.json
  package.json
  src/wrappidApp.js
  test/service.test.js
  wrappid.conf.json
Labels: enhancement
